#Sprint 11 - add-database
MarychevDmitry/java-filmorate pull request #20
Opened 2023-09-30 22:55 UTC by MarychevDmitry

Реализован весь функционал описанный в ТЗ.
Хранение данных вынесено в базу данных. (Схема базы данных в README).
Добавлен статус дружбы между пользователями. true если оба пользователя добавили друг друга в друзья. Иначе false. 
Для фильмов добавлен Жанр и Возростной Рейтинг.

2023-10-01 09:06 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но есть что подкрутить

1) Убрать точки в логах - рекомендация
2) Давай введем в практику добавлять javadoc в ентити, краткий буквально 2-3 слова
3) Доработаем исключения

Буду ждать с правками =)

2023-10-01 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +            throw new MpaNotFoundException(String.format("Mpa with id %s. not found.", id));
Аналогично подумай как избежать написания текста в исключение каждый раз

2023-10-01 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +            throw new MpaNotFoundException("Mpa not found.");
А такое исключение когда возникнет? Помоему если мы тут ловим исключение то происходит что-то другое а не отсутствие MPA

2023-10-01 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return setLikesInFilm(jdbcTemplate.query(sqlQuery, this::mapFilm));
Выглядит сложновато, давай попробуем разбить на строки и надо еще подумать, а точно ли нам в фильме нужны лайки всегда? Или можно их отдельно подгружать если нужно

2023-10-01 09:06 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +@Component
На интерфейсах обычно не ставят такую аннотацию

2023-10-01 09:06 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
not null маловато вроде как в схеме

рекомендую primary key делать как constraint внизу в определение таблицы, но это не обязательно

2023-10-01 21:04 UTC, MarychevDmitry commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Mpa mpa;
В ревью 9 спринта отказались от анотаций ибо сложно отследить где она вызывается. 
Все проверки вынес в отдельные классы валидации. 
Добавил проверку MPA в FilmValidator.

![Снимок экрана 2023-10-01 235158](https://github.com/MarychevDmitry/java-filmorate/assets/130239384/23ac03d4-82ff-446c-ac29-d7a3b77927d6)

https://github.com/MarychevDmitry/java-filmorate/pull/18#discussion_r1314437883

2023-10-01 21:04 UTC, MarychevDmitry commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private String name;
Проверяется в FilmValidator

2023-10-01 21:05 UTC, MarychevDmitry commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private LocalDate releaseDate;
Добавил проверку FilmValidator

2023-10-01 21:05 UTC, MarychevDmitry commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Integer duration;
Проверяется в FilmValidator

2023-10-01 21:07 UTC, MarychevDmitry commented on src/main/java/ru/yandex/practicum/filmorate/service/MpaService.java
> +            throw new MpaNotFoundException("Mpa not found.");
Возникает при NPE если 1 из id = null 
Изменил компоратор в сортировке, теперь достаточно только MpaNotFoundException

2023-10-01 21:58 UTC, merged

2023-10-02 04:34 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Mpa mpa;
Согласен, что валидация должна быть отдельной, а не зависить на аннотациях в ентити.
Тут я скорее сделал коммент с мыслью "непонятно может ли сущность быть null" 
Это еще решается @Column (nullable = true/false) вот таким подходом, но это обычно в Spring Data JPA делается.
Т.е чтобы другие разработчики глядя на ентити понимали что обязательные поля, а что нет.

2023-10-02 04:40 UTC, krylov-sergey-sergeevich reviewed
Привет, вижу правки - зачет